all_events_list = [
    "Approach",
    "Approach contact",
    "Approach rear",
    "Behind",
    "Break contact",
    "Center Zone",
    "Contact",
    "Detection",
    "Escape",
    "Follow",
    "FollowZone",
    "Get away",
    "Group 3 break",
    "Group 3 make",
    "Group 4 break",
    "Group 4 make",
    "Group2",
    "Group3",
    "Group4",
    "Head detected",
    "Look down",
    "MACHINE LEARNING",
    "ASSOCIATION",
    "Move in contact",
    "Move isolated",
    "Nest3_",
    "Nest4_",
    "Oral-genital Contact",
    "Oral-oral Contact",
    "Periphery Zone",
    "RFID ASSIGN ANONY-MOUS TRACK",
    "RFID MATCH",
    "RFID MISMATCH",
    "Rear at periphery",
    "Rear in centerWindow",
    "Rear in contact",
    "Rear isolated",
    "Rearing",
    "SAP",
    "Side by side Contact Side by side Contact, opposite way",
    "Social approach",
    "Social escape",
    "Stop",
    "Stop in contact",
    "Stop isolated",
    "Train2",
    "WallJump",
    "Water Stop",
    "Water Zone",
    "badIdentity",
    "badOrientation",
    "badSegmentation",
    "coucou",
    "event",
    "manualContact",
    "manualOralGenital",
    "manualOralOralContact",
    "manualSideSideOpposite",
    "manualSideSideSame",
    "seq oral geni - oral oral",
    "seq oral oral - oral genital"
]

generic_events_list = [
    "Look down",
    "Center Zone",
    "Stop",
    "Rearing",
    "Contact",
    "Oral-genital Contact",
    "Oral-oral Contact",
    "Approach",
    "Group2",
    "Group3",
    "Group4",
    "badIdentity",
    "badOrientation",
    "badSegmentation",
    "flickering",
]

sorted_events_list = {
    "alone": [
        "Look down",
        "Center Zone",
        "Stop",
        "Rearing",
        ],
    "social": [
        "Contact",
        "Oral-genital Contact",
        "Oral-oral Contact",
        "Approach",
        "Group2",
        "Group3",
        "Group4",
        ],
    "debug": [
        "badIdentity",
        "badOrientation",
        "badSegmentation",
        "flickering",
    ]
}