from lmtanalysis import (
    BuildEventApproachContact,
    BuildEventApproachRear,
    BuildEventCenterPeripheryLocation,
    BuildEventDetection,
    BuildEventExclusiveCleanOralOralSideSideNoseAnogenitalContact,
    BuildEventExclusiveMoveStopIsolated,
    BuildEventExclusiveUndetected,
    BuildEventFlickering,
    BuildEventFloorSniffing,
    BuildEventFollowZone,
    BuildEventGetAway,
    BuildEventGroup2,
    BuildEventGroup3,
    BuildEventGroup3MakeBreak,
    BuildEventGroup4,
    BuildEventGroup4MakeBreak,
    BuildEventHouse,
    BuildEventHuddling,
    BuildEventInCorner,
    BuildEventLongChase,
    BuildEventMove,
    BuildEventMoveSpeedCategories,
    BuildEventMoveSpeedCategories2,
    BuildEventNest3,
    BuildEventNest4,
    BuildEventObjectSniffingNor,
    BuildEventObjectSniffingNorAcquisitionWithConfig,
    BuildEventObjectSniffingNorTestWithConfig,
    BuildEventOnHouse,
    BuildEventOralGenitalContact,
    BuildEventOralOralContact,
    BuildEventOralSideSequence,
    BuildEventOtherContact,
    BuildEventPassiveAnogenitalSniff,
    BuildEventRear5,
    BuildEventRearCenterPeriphery,
    BuildEventSAP,
    BuildEventSideBySide,
    BuildEventSideBySideOpposite,
    BuildEventSocialApproach,
    BuildEventSocialEscape,
    BuildEventStop,
    BuildEventTrain2,
    BuildEventTrain3,
    BuildEventTrain4,
    BuildEventWallJump,
    BuildEventWaterPoint,
)


complete_event_list = {
    "Approach": None,
    "Approach contact": BuildEventApproachContact,
    "Approach rear": BuildEventApproachRear,
    "Behind": None,
    "Break contact": None,
    "Center Zone": BuildEventCenterPeripheryLocation,
    "Periphery Zone": "Center Zone",
    "Contact": None,
    "Detection": BuildEventDetection,
    "Escape": None,
    "Flickering": BuildEventFlickering,
    "Floor sniffing": BuildEventFloorSniffing,
    "Follow": None,
    "FollowZone": BuildEventFollowZone,
    "Get away": BuildEventGetAway,
    "Group 3 break": BuildEventGroup3MakeBreak,
    "Group 3 make": "Group 3 break",
    "Group 4 break": BuildEventGroup4MakeBreak,
    "Group 4 make": "Group 4 break",
    "Group2": BuildEventGroup2,
    "Group3": BuildEventGroup3,
    "Group4": BuildEventGroup4,
    "in house corner": BuildEventHouse,
    "over house": "in house corner",
    "Head detected": None,
    "Huddling": BuildEventHuddling,
    "Corner": BuildEventInCorner,
    "Corner 0": "Corner",
    "Corner 1": "Corner",
    "Corner 2": "Corner",
    "Corner 3": "Corner",
    "longChase": BuildEventLongChase,
    "Look down": None,
    "MACHINE LEARNING": None,
    "Move": BuildEventMove,
    "Move isolated": "Move",
    "Move in contact": "Move",
    "Move high speed": BuildEventMoveSpeedCategories2,
    "ASSOCIATION": None,
    "Nest3_": BuildEventNest3,
    "Nest4_": BuildEventNest4,
    "SniffLeft": BuildEventObjectSniffingNor,
    "SniffRight": "SniffLeft",
    "onHouse": BuildEventOnHouse,
    "Oral-genital Contact": BuildEventOralGenitalContact,
    "Oral-oral Contact": BuildEventOralOralContact,
    "seq oral oral - oral genital": BuildEventOralSideSequence,
    "seq oral geni - oral oral": "seq oral oral - oral genital",
    "Other contact": BuildEventOtherContact,
    "Passive oral-genital Contact": BuildEventPassiveAnogenitalSniff,
    "Rearing": None,
    "Rear in contact": BuildEventRear5,
    "Rear isolated": "Rear in contact",
    "Rear at periphery": BuildEventRearCenterPeriphery,
    "Rear in centerWindow": "Rear at periphery",
    "RFID ASSIGN ANONY-MOUS TRACK": None,
    "RFID MATCH": None,
    "RFID MISMATCH": None,
    "SAP": BuildEventSAP,
    "Side by side Contact": BuildEventSideBySide,
    "Side by side Contact, opposite way": BuildEventSideBySideOpposite,
    "Social approach": BuildEventSocialApproach,
    "Social escape": BuildEventSocialEscape,
    "Stop": None,
    "Stop in contact": BuildEventStop,
    "Stop isolated": BuildEventStop,
    "Train2": BuildEventTrain2,
    "Train3": BuildEventTrain3,
    "Train4": BuildEventTrain4,
    "WallJump": BuildEventWallJump,
    "Water Stop": BuildEventWaterPoint,
    "Water Zone": "Water Stop",
    "badIdentity": None,
    "badOrientation": None,
    "badSegmentation": None,
    "coucou": None,
    "event": None,
    "manualContact": None,
    "manualOralGenital": None,
    "manualOralOralContact": None,
    "manualSideSideOpposite": None,
    "manualSideSideSame": None,
}


ICM_event_list = {
    "Break contact": None,
    "Contact": None,
    "Detection": BuildEventDetection,
    "Flickering": BuildEventFlickering,
    "Head detected": None,
    "Move": BuildEventMove,
    "Move isolated": "Move",
    "Move in contact": "Move",
    "Oral-oral Contact": BuildEventOralOralContact,
    "RFID MATCH": None,
    "RFID MISMATCH": None,
    "Side by side Contact": BuildEventSideBySide,
    "Side by side Contact, opposite way": BuildEventSideBySideOpposite,
    "Stop": None,
    "Stop in contact": BuildEventStop,
    "Stop isolated": BuildEventStop,
}
